### ISSUE TITLE
websocket not working!

### ISSUE THREAD

**Issue by 960590968** [hbdmapi/huobi_usdt_swap_Java#4]
2021-05-21 11:17:24.126 [ERROR] [WebSocketConnectReadThread-15] [com.huobi.wss.handle.WssMarketHandle.onError:98] - onError:
java.net.ConnectException: Operation timed out (Connection timed out)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:395)
	at java.base/java.lang.Thread.run(Thread.java:835)
2021-05-21 11:17:24.129 [ERROR] [WebSocketConnectReadThread-15] [com.huobi.wss.handle.WssMarketHandle.onClose:93] - onClose i:-1,s:Operation timed out (Connection timed out),b:false

**Comment by 960590968** [comment]
websocket连接超时是什么原因？

**Comment by fuwei6056** [comment]
可以说明一下是接用那个推送接口，使用的是那个域名来访问的吗？

**Comment by 960590968** [comment]
> 可以说明一下是接用那个推送接口，使用的是那个域名来访问的吗？


![image](https://user-images.githubusercontent.com/16714679/119105044-8b77d080-ba4f-11eb-91c9-e3311ddc)

**Comment by 960590968** [comment]
> 可以说明一下是接用那个推送接口，使用的是那个域名来访问的吗？

![image](https://user-images.githubusercontent.com/16714679/119105316-c67a0400-ba4f-11eb-849e-71bfb417a3c6.png)

我直接跑的测试用例

**Comment by fuwei6056** [comment]
老板，是用国内的服务器测试的吧？可以使用api. hbdm. vn这个域名试一下。发自我的华为手机-------- 原始邮件 --------发件人： 960590968 ***@***.***>日期： 2021年5月21日周五 16:16收件人： hbdmapi/huobi_usdt_swap_Java ***@***.***>抄送： fuwei6056 ***@***.***>, Comment ***@***.***>主    题： Re: [hbdmapi/huobi_usdt_swap_Java] websocket not working! (#4)



可以说明一下是接用那个推送接口，使用的是那个域名来访问的吗？





我直接跑的测试用例

**Comment by 960590968** [comment]
> api.hbdm.vn域名可以，谢谢了。虽然是国内，但是我用了梯子，为啥api.hbdm.com的http是可以的，但是ws不行。

**Comment by fuwei6056** [comment]
可能是梯子的网络不是太稳定，也以才会超时发自我的华为手机-------- 原始邮件 --------发件人： 960590968 ***@***.***>日期： 2021年5月21日周五 19:37收件人： hbdmapi/huobi_usdt_swap_Java ***@***.***>抄送： fuwei6056 ***@***.***>, Comment ***@***.***>主    题： Re: [hbdmapi/huobi_usdt_swap_Java] websocket not working! (#4)



api.hbdm.vn域名可以，谢谢了。虽然是国内，但是我用了梯子，为啥api.hbdm.com的http是可以的，但是ws不行。
