### ISSUE TITLE
执行mvn install，到test这步时会报错卡住，该如何处理呢？

### ISSUE THREAD

**Issue by ppmmmmpp** [hbdmapi/huobi_usdt_swap_Java#6]
FangdeMacBook-Pro:huobi_usdt_swap_Java-master fangzheng$ mvn install
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------< com.huobi.linear.swap.api:huobi-linear-swap-api >-----------
[INFO] Building huobi-linear-swap-api 1.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ huobi-linear-swap-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ huobi-linear-swap-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 207 source files to /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/target/classes
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/market/LinearSwapPremiumIndexKlineResponse.java:[6,23] sun.rmi.runtime.Log是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/account/SwapMasterSubTransferRecordResponse.java:[7,23] sun.rmi.runtime.Log是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/account/SwapApiTradingStatusResponse.java:[7,23] sun.rmi.runtime.Log是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/account/SwapAccountPositionInfoResponse.java:[4,38] com.sun.imageio.plugins.common.BogusColorSpace是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/market/LinearSwapPremiumIndexKlineResponse.java:[6,23] sun.rmi.runtime.Log是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/account/SwapMasterSubTransferRecordResponse.java:[7,23] sun.rmi.runtime.Log是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/account/SwapApiTradingStatusResponse.java:[7,23] sun.rmi.runtime.Log是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/account/SwapAccountPositionInfoResponse.java:[4,38] com.sun.imageio.plugins.common.BogusColorSpace是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/market/LinearSwapPremiumIndexKlineResponse.java:[6,23] sun.rmi.runtime.Log是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/account/SwapMasterSubTransferRecordResponse.java:[7,23] sun.rmi.runtime.Log是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/account/SwapApiTradingStatusResponse.java:[7,23] sun.rmi.runtime.Log是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/account/SwapAccountPositionInfoResponse.java:[4,38] com.sun.imageio.plugins.common.BogusColorSpace是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/market/LinearSwapPremiumIndexKlineResponse.java:[6,23] sun.rmi.runtime.Log是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/account/SwapMasterSubTransferRecordResponse.java:[7,23] sun.rmi.runtime.Log是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/account/SwapApiTradingStatusResponse.java:[7,23] sun.rmi.runtime.Log是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/account/SwapAccountPositionInfoResponse.java:[4,38] com.sun.imageio.plugins.common.BogusColorSpace是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/market/LinearSwapPremiumIndexKlineResponse.java:[6,23] sun.rmi.runtime.Log是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/account/SwapMasterSubTransferRecordResponse.java:[7,23] sun.rmi.runtime.Log是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/account/SwapApiTradingStatusResponse.java:[7,23] sun.rmi.runtime.Log是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/main/java/com/huobi/api/response/account/SwapAccountPositionInfoResponse.java:[4,38] com.sun.imageio.plugins.common.BogusColorSpace是内部专用 API, 可能会在未来发行版中删除
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ huobi-linear-swap-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ huobi-linear-swap-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 11 source files to /Users/fangzheng/OneDrive/WorkSpace/Develop/MacWorkspace/huobi_usdt_swap_Java-master/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ huobi-linear-swap-api ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.huobi.linear.swap.wss.WssMarketSubTest
2021-08-25 17:19:00.756 [ERROR] [WebSocketConnectReadThread-13] [com.huobi.wss.handle.WssMarketHandle.onError:98] - onError:
java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.Socket.connect(Socket.java:589)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:395)
	at java.lang.Thread.run(Thread.java:748)
2021-08-25 17:19:00.763 [ERROR] [WebSocketConnectReadThread-13] [com.huobi.wss.handle.WssMarketHandle.onClose:93] - onClose i:-1,s:Operation timed out (Connection timed out),b:false

**Comment by fuwei6056** [comment]
你先mvn clean 一下。再mvn install. 如果还是不行，就将项目删除掉然后在重新拉一下。我这边试了一下，拉下来是可以直接用的。

**Comment by ppmmmmpp** [comment]
> 你先mvn clean 一下。再mvn install. 如果还是不行，就将项目删除掉然后在重新拉一下。我这边试了一下，拉下来是可以直接用的。

试了一下情况还是一样。看到错误提示是某个东西网络连接超时，会不会和网络环境有关系，比如网络必须是在墙外？我是在国内网络环境下执行的mvn install
